// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ropot_Anastasia.Data;

#nullable disable

namespace Ropot_Anastasia.Migrations
{
    [DbContext(typeof(Ropot_AnastasiaContext))]
    partial class Ropot_AnastasiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ropot_Anastasia.Models.Data_Examen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<decimal>("Data_Ex")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("Data_Examen");
                });

            modelBuilder.Entity("Ropot_Anastasia.Models.Examen", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("DataExamen")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Data_ExID")
                        .HasColumnType("int");

                    b.Property<string>("Materie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profesor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sala")
                        .HasColumnType("decimal(6,0)");

                    b.HasKey("ID");

                    b.HasIndex("Data_ExID");

                    b.ToTable("Examen");
                });

            modelBuilder.Entity("Ropot_Anastasia.Models.Examen", b =>
                {
                    b.HasOne("Ropot_Anastasia.Models.Data_Examen", "Data_Ex")
                        .WithMany("Examene")
                        .HasForeignKey("Data_ExID");

                    b.Navigation("Data_Ex");
                });

            modelBuilder.Entity("Ropot_Anastasia.Models.Data_Examen", b =>
                {
                    b.Navigation("Examene");
                });
#pragma warning restore 612, 618
        }
    }
}
